credentials:
  usernames:
    willbankmmm:
      email: geethu4444@gmail.com
      name: Geetakrishna
      password: '$2b$12$mk8xyS2uF7UApxJU/fyASuV7dnwEtKN9dUW0qxH4ox4VwZyLLbCXK'
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - geethu4444@gmail.com
